management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, logfile, loggers
    enabled-by-default: false

  endpoint:
    health:
      show-details: always
      enabled: true
    logfile:
      enabled: true
      external-file: logs/logfile.log
    metrics:
      enabled: true
    info:
      enabled: true
    loggers:
      enabled: true
    shutdown:
      enabled: true

  health:
    defaults:
      enabled: true

logging:
  file:
    path: logs
    name: logs/logfile.log

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka
    register-with-eureka: true
    fetch-registry: true

  instance:
    leaseRenewalIntervalInSeconds: 30
    leaseExpirationDurationInSeconds: 90
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
