spring:
  data:
    mongodb:
      database: hw18_book
      uri: mongodb://localhost
      port: 27017

mongock:
  runner-type: InitializingBean
  change-logs-scan-package:
    - ru.otus.book.config.changelog

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka
    register-with-eureka: true
    fetch-registry: true

  instance:
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 90
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true

feign:
  client:
    config:
      default:
        connectTimeout: 1000
        readTimeout: 1000
        loggerLevel: basic

book-service:
  ribbon:
    eager-load:
      enabled: true
  ServerListRefreshInterval: 1000
