spring:
  data:
    mongodb:
      database: hw18_book
      uri: mongodb://localhost
      port: 27017

mongock:
  runner-type: InitializingBean
  change-logs-scan-package:
    - ru.otus.book.config.changelog

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 2
    healthcheck:
      enabled: true

  instance:
    lease-renewal-interval-in-seconds: 2
    lease-expiration-duration-in-seconds: 5
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

book-service:
  ribbon:
    eager-load:
      enabled: true
    MaxConnectionsPerHost: 1000
    MaxTotalConnections: 3000
    ReadTimeout: 2000
    ConnectTimeout: 2000
    MaxAutoRetries: 0
    MaxAutoRetriesNextServer: 0
    ServerListRefreshInterval: 5000

management:
  endpoints:
    web:
      exposure:
        include: '*'

hystrix:
  command:
    getGenreByName:
      fallback:
        enabled: true
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 3000
      metrics:
        rollingStats:
          timeInMilliseconds: 15000
      circuitBreaker:
        enabled: true
        requestVolumeThreshold: 3
        errorThresholdPercentage: 50
        sleepWindowInMilliseconds: 50000

    getAuthorByLastName:
      fallback:
        enabled: true
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 3000
      metrics:
        rollingStats:
          timeInMilliseconds: 15000
      circuitBreaker:
        enabled: true
        requestVolumeThreshold: 3
        errorThresholdPercentage: 50
        sleepWindowInMilliseconds: 50000
