eureka:
  server:
    max-threads-for-peer-replication: 0
    enable-self-preservation: false #default true
    eviction-interval-timer-in-ms: 5000 #default 60000
    response-cache-update-interval-ms: 1000 #default 30000
    use-read-only-response-cache: false

  client:
    fetchRegistry: false
    register-with-eureka: false


  instance:
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 1
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true

eureka-service:
  ServerListRefreshInterval: 1000

