spring:
  data:
    mongodb:
      database: hw08
      uri: mongodb://localhost
      port: 27017

  mongock:
    changelogs: "ru.otus.hw08.impl.changelogs"

  shell:
    interactive:
      enabled: true

logging:
  level:
    ROOT: INFO
