spring:
  data:
    mongodb:
      database: hw13
      uri: mongodb://localhost
      port: 27017

mongock:
  runner-type: InitializingBean
  change-logs-scan-package:
    - ru.otus.hw13.config.changelog

logging:
  level:
    ROOT: INFO
