spring:
  data:
    mongodb:
      database: hw18_comment
      uri: mongodb://localhost
      port: 27017

mongock:
  runner-type: InitializingBean
  change-logs-scan-package:
    - ru.otus.comment.config.changelog
