spring:
  data:
    mongodb:
      database: hw18_author
      uri: mongodb://localhost
      port: 27017

mongock:
  runner-type: InitializingBean
  change-logs-scan-package:
    - ru.otus.author.config.changelog

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 1
    healthcheck:
      enabled: true

  instance:
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 1
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true

author-service:
  ribbon:
    eager-load:
      enabled: true
    MaxConnectionsPerHost: 1000
    MaxTotalConnections: 3000
    ReadTimeout: 10000
    ConnectTimeout: 2000
    MaxAutoRetries: 0
    MaxAutoRetriesNextServer: 0
    ServerListRefreshInterval: 1000
