spring:
  data:
    mongodb:
      database: hw18_author
      uri: mongodb://localhost
      port: 27017

mongock:
  runner-type: InitializingBean
  change-logs-scan-package:
    - ru.otus.author.config.changelog
