spring:
  data:
    mongodb:
      database: ${mongo.db.name:hw17}
#      uri: ${MONGO_URI:mongodb://localhost}
      port: ${mongo.port:27017}
      host: ${mongo.host:localhost}
    rest:
      basePath: /rest
  application:
    name: hw17Name

mongock:
  runner-type: InitializingBean
  change-logs-scan-package:
    - ru.otus.hw17.config.changelog

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus, logfile, loggers
    enabled-by-default: false
    jmx:
      exposure:
        include: '*'

  endpoint:
    health:
      show-details: always
      enabled: true
    logfile:
      enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true
    info:
      enabled: true
    loggers:
      enabled: true
    shutdown:
      enabled: true

  health:
    defaults:
      enabled: true

logging:
  level:
    ROOT: INFO

