spring:
  data:
    mongodb:
      database: hw16
      uri: mongodb://localhost
      port: 27017
    rest:
      basePath: /rest

mongock:
  runner-type: InitializingBean
  change-logs-scan-package:
    - ru.otus.hw16.config.changelog

logging:
  level:
    ROOT: INFO

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      enabled: true

