spring:
  data:
    mongodb:
      database: hw16
      uri: mongodb://localhost
      port: 27017
    rest:
      basePath: /rest
  application:
    name: hw16Name

mongock:
  runner-type: InitializingBean
  change-logs-scan-package:
    - ru.otus.hw16.config.changelog

logging:
  level:
    ROOT: INFO
  file:
    name: ./logs/logging_file.log

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
    enabled-by-default: false
    jmx:
      exposure:
        include: '*'

  endpoint:
    health:
      show-details: always
      enabled: true

    logfile:
      enabled: true
      cache:
        time-to-live: 10

    metrics:
      enabled: true

    prometheus:
      enabled: true

    info:
      enabled: true

    shutdown:
      enabled: true

  health:
    defaults:
      enabled: true



